### ISSUE TITLE
Custom date input does not reflect first day of the week

### ISSUE THREAD

**Issue by Liggliluff** [DJDavid98/HammerTime#123]
Right now when using HammerTime in Swedish, the calendar appears like this:
![image](https://user-images.githubusercontent.com/822352/222852289-f5cc9af6-4a60-4236-be0b-ae346d0ca55c.png)
It appears with Sunday (Sö) first, when the standard for Sweden is Monday (Må). This issue is also seen with English, UK, español, italiano and so on.

Further are minor issues, such as how the weekday names starts with a capital letter, when this isn't the case in for example Windows, where it's written as "må ti on to fr lö sö". Second issue is that Saturdays are marked in red, when in Sweden, only Sunday and official holidays are red days. Marking non-red days in red just looks wrong.

Similar issue with the red days is the case for when using Hebrew (Israel) where Saturday and Sunday are still marked in red, despite the official weekend in the country is Friday and Saturday. Their work week is Sunday through Thursday.

**Comment by DJDavid98** [comment]
Thank you for reporting these issues, the wrong first day of week was a coding error,trying to read the information from a locale called `'locale'` instead of the current language, and as for the weekend days the date libraries do not provide which days should be marked red, so it takes the default Saturday and Sunday. I've updated the code for Swedish and Hebrew based on your suggestion and I will reach out to the translators to get this information for other languages.

**Comment by Liggliluff** [comment]
Unicode has territory information regarding this: https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/territory_information.html

Default for all regions it is Sat-Sun for the weekend, _but_ that doesn't mean both days are red days.
For regions where the weekend is different:
```
Thu-Fri: AF
Fri-Fri: IR
Fri-Sat : BH DZ EG IL IQ JO KW LY OM QA SA SD SY YE
Sun-Sun : IN UG
```
So for Sweden, the weekend is Sat-Sun, but only Sun is red.

Looking for other calendars from different sources: [Germany](https://www.kalenderpedia.de/download/kalender-2023-querformat-jahresuebersicht-in-farbe.pdf), [Switzerland](https://www.kalenderpedia.de/download/schweiz/kalender-2023-schweiz-querformat-jahresuebersicht-in-farbe.pdf), [Austria](https://www.kalenderpedia.de/download/oesterreich/kalender-2023-oesterreich-querformat-jahresuebersicht-in-farbe.pdf), but it's hard to find any good sources for this information. There's a lot of random sites ... [Spain](https://www.ull.es/estudios-docencia/wp-content/uploads/sites/7/2022/06/280882943_10158680089571099_2231918960816456383_n.jpg)

Would be good if CLDR did have information about red days, so most probably just avoid including them.

**Comment by DJDavid98** [comment]
Due to a bug I had to set the option that controls which days are red to a fixed empty list if the values are not known yet, because the library wasn't using the defaults in some cases. In effect this means that until manually specified, a locale will have no weekend days associated. I'll add the info to the locales gradually as I get feedback from the translators.
