### ISSUE TITLE
time picker doesn't work on Firefox mobile

### ISSUE THREAD

**Issue by UltimateRiff** [DJDavid98/HammerTime#153]
when I try and select a time (both with the combined and seperate date/time pickers), it doesn't let me choose an hour or minute, only seconds for the current time.

![Screenshot_20230802-134352](https://github.com/DJDavid98/HammerTime/assets/100507157/7c686470-c9c7-4cac-bf64-0b758488347d)

I'm on Android with Firefox. I will also note it does work properly on Chrome

**Comment by DJDavid98** [comment]
I added a temporary workaround that disables the seconds part of the input only on mobile Firefox, I hope that will be enough to make the site at least mostly usable without having to resort to a different browser.

The only caveat of this is that pressing the "set current time" button will set a timestamp with the seconds of the current system clock but you will not be able to change the seconds due to this restriction. Still a better trade-off than not being able to change the other two components at all, so I'll leave it at that for now.

**Comment by xobs** [comment]
I couldn't get it to work at all today either - the "set" button on the picker would just set the current time, and the fields themselves weren't editable.

**Comment by DJDavid98** [comment]
This is an issue in the Firefox Mobile browser and it seems to get worse by the day. Unfortunately your options are to use a different browser, or alternatively you can give https://sledgehammerti.me/ a try. It's a work-in-progress alternative site where I'm planning to have fully custom components for date and time input that should hopefully not be affected by bugs like this. Its UI is still very much in the early stages, but the very basic functionality works at least. Until that project is done and replaces this one, I expect this issue to remain open.
