### ISSUE TITLE
Site can't be reached

### ISSUE THREAD

**Issue by Broskisupps** [DJDavid98/HammerTime#64]
The website can't be reached when I attempt to access it on all browser platforms, both PC and mobile.

**Comment by DJDavid98** [comment]
The website is up and operational, most likely you have a DNS issue. Please take a look at https://www.opendns.com/setupguide/ to change your DNS servers and see if the problem persists.

**Comment by Lyrratic** [comment]
I checked my DNS servers and tried changing to OpenDNS but am still having this issue as well. It's been 2 or 3 days since I first noticed the issue. 
![image](https://user-images.githubusercontent.com/6866177/167778538-13391b24-2906-4488-b831-b52cd0434a1f.png)

**Comment by DJDavid98** [comment]
Seems like your ISP or some other security software is blocking the new domain. The app is also available under an laternative URL that you might have better luck with: https://hammertime-djdavid98.vercel.app/

**Comment by Lyrratic** [comment]
That alternative URL works! Thanks so much. I think you're right that it's probably my ISP; I tried again on my phone through cellular data instead of wifi and the original url worked fine.

**Comment by DJDavid98** [comment]
To the original poster: I'm closing this issue, since the alternative URL mentioned above or [the Discord bot](https://discord.com/oauth2/authorize?scope=bot%20applications.commands&client_id=964106782790283295&permissions=0) should be sufficient alternatives in case the main domain is blocked. Please use these instead.
