### ISSUE TITLE
Default Timezone to user's current timezone

### ISSUE THREAD

**Issue by Kurohyou** [DJDavid98/HammerTime#98]
The need to specify a timezone when using the Hammertime bot kind of defeats the purpose of having the bot in a channel. Ideally, the bot would know what timezone a user is in when they call the `/timestamp` command and the `timezone` options should default to the user's timezone.

This matches what I imagine is the primary use case of the bot, which is to give your local time so that everyone on the channel sees it in their own local time. The use case of wanting to specify a time in a different timezone from your local timezone is most likely an edge case.

EDIT: This would then also match the behavior of the website, which defaults to the user's system timezone.

**Comment by DJDavid98** [comment]
This is an issue for [HammerTimeBot](https://github.com/DJDavid98/HammerTimeBot), not this repository, but I'll answer it here:

On the site I have a lot more information to work with, e.g. I can get the system timezone so you don't have to specify it manually. Discord does not store nor send user timezone data when users execute slash commands, so in order to not have to specify this each time I'd need a mechanism to keep track of timezones for users and you would have to update your default in case your location changes.

I have no plans to add additional storage and complexity to the bot just for this, so unfortunately you will need to specify the timezone each time when using it.

**Comment by Kurohyou** [comment]
Ah, wasn't aware of those limitations. Thanks for the information!
